Учебный проект: обратная сторона реальности
htmlacademy-react/54972-guess-melody-5 pull request #4
Opened 2020-10-11 17:07 UTC by AeShevch

2020-10-12 09:51 UTC, abeluzhenko requested changes

2020-10-12 09:51 UTC, abeluzhenko commented on markup/fail-tries.html
> +        <div class="result__logo"><img src="/img/melody-logo.png" alt="Угадай мелодию" width="186" height="83"></div>
Можно просто добавить  `<base href="/">` в секцию `head`, тогда ссылки будут работать без изменений (в лекции это было).

2020-10-12 09:51 UTC, abeluzhenko commented on src/components/abstract-game-component/abstract-game-component.jsx
> +import React from "react";
Очень круто, что ты решил вынести общий код в одно место и понимаешь, как использовать для этого наследование. Но я бы предложил использовать немного другой подход здесь. Вместо создания иерархии классов, можно было бы создать общий компонент, который принимал бы в качестве пропса функцию, или React-элемент и рендерил бы его в нужном месте, вместо вызова `_renderGame`.
Т.е. я предлагаю использовать композицию вместо наследования. Это более соотвествует философии реакта и позволит упростить код (не нужно будет проверять вызов абстрактных методов, не будет строгой привязки к иерархии). 

Если же решишь оставить текущий вариант, то надо придумать, как избавиться нарушения принципов SOLID (они есть в текущей реализации)

2020-10-12 12:09 UTC, AeShevch commented on markup/fail-tries.html
> +        <div class="result__logo"><img src="/img/melody-logo.png" alt="Угадай мелодию" width="186" height="83"></div>
Да, я кстати добавил, но уже после того, как ссылки поменял. Забыл убрать)

2020-10-12 12:11 UTC, AeShevch commented on src/components/abstract-game-component/abstract-game-component.jsx
> +import React from "react";
Спасибо за комментарии, буду исправлять!

2020-10-13 08:14 UTC, abeluzhenko requested changes

2020-10-13 08:14 UTC, abeluzhenko commented on src/components/game/game.jsx
> +              ? <QuestionArtistScreen question={currentQuestion} handleSubmit={this._handleSubmit}/>
Можно пропсы `{ question: currentQuestion, handleSubmit: this._handleSubmit }` вынести в отдельную константу и передавать в эти компоненты через rest-оператор: {...props}, чтобы не дублировать этот код.

2020-10-13 08:14 UTC, abeluzhenko commented on src/components/question-genre-screen/question-genre-screen.jsx
> +                  value={`answer-${index}`}
Можно здесь передавать `index`, без преффикса `'answer-'`, тогда потом, при обработке ответа будет проще парсить его номер.

2020-10-13 08:14 UTC, abeluzhenko commented on src/components/question-artist-screen/question-artist-screen.jsx
> +    const {handleSubmit, handleChange, question} = this.props;
`handleChange` нужно тоже описать в `propTypes`

2020-10-13 08:34 UTC, AeShevch commented on src/components/button-start/button-start.jsx
> +const ButtonStart = withRouter(({history}) => (
Для Link бы просто стили пришлось править) Сейчас поменяю

2020-10-18 10:40 UTC, abeluzhenko approved these changes

2020-10-18 10:40 UTC, abeluzhenko commented on src/components/game/game.jsx
> +    const props = {
Лучше как-то утончить название, вроде `contentProps`

2020-10-18 10:40 UTC, merged