Учебный проект: больше подробностей
htmlacademy-react/54972-guess-melody-5 pull request #5
Opened 2020-10-18 19:57 UTC by AeShevch

2020-10-19 07:17 UTC, abeluzhenko requested changes

2020-10-19 07:17 UTC, abeluzhenko commented on src/components/question-genre-screen/question-genre-screen.jsx
> +                    activePlayer: activePlayer === index ? -1 : index
Здесь было бы красиво завести константу вроде `EMPTY_ID`, чтобы не использовать "магическое значение" -1

2020-10-19 07:17 UTC, abeluzhenko commented on src/mocks/questions.js
> +    id: nanoid(),
Можно было бы еще как-то так сделать, чтобы не дублировать код генерации id `export default [...].map(item => ({  ...item, id: nanoid() }))`

2020-10-19 07:17 UTC, abeluzhenko commented on src/components/audioPlayer/audioPlayer.jsx
> +            onCanPlayThrough={() => this.setState({isLoading: false})}
Очень круто, что ты сделал так, а не как предлагали в лекции. Этот способ гораздо чище и "реактивнее".

2020-10-19 08:42 UTC, AeShevch commented on src/mocks/questions.js
> +    id: nanoid(),
Понял, только академия почему-то не разрешает объединять объекты через spread, только через Object.assign

2020-10-20 06:05 UTC, abeluzhenko approved these changes

2020-10-20 06:05 UTC, abeluzhenko commented on src/mocks/questions.js
> +      id: nanoid(),
Теперь можно это удалить)

2020-10-20 06:05 UTC, merged